### ISSUE TITLE
Bearer Token SCIM endpoint authentication support

### ISSUE THREAD

**Issue by patrick4njos** [suvera/keycloak-scim2-storage#2]
Very interesting your project.

I would like to use your project to integrate with AWS SSO, but I noticed that AWS doesn't use "User" and "Password" for SCIM endpoint integration instead they use "Bearer Token"...

I would like to know if the project can support this type of authentication?

Thanks 

Ref: https://docs.aws.amazon.com/singlesignon/latest/userguide/provision-automatically.html

**Comment by suvera** [comment]
Hi @patrick4njos  yes, 'll look into it, and let you know.

**Comment by suvera** [comment]
This is done.  Bearer Token has been added to User Federation screen.
