### ISSUE TITLE
Error getting realm from database during sync job execution

### ISSUE THREAD

**Issue by sl-benoitoyez** [suvera/keycloak-scim2-storage#4]
Hello,

Now that I could start a SCIM synchronization job successfully, it is raising a new error:
![image](https://user-images.githubusercontent.com/77098658/154448776-d1d74aee-4337-4dbd-8df3-0cd142ebe3e6.png)

I checked and this is pointing to this line:  https://github.com/suvera/keycloak-scim2-storage/blob/master/src/main/java/dev/suvera/keycloak/scim2/storage/storage/Scim2SyncJob.java#L83

I'm currently testing the module in a Keycloak 11.0.3 (pretty close to the version you have in your README example)

I noticed that Keycloak is using different realm ids depending on the API used ("id" or "name" sometimes, at least in my version) so I tried to store the name in the job definition instead: https://github.com/axel-springer-kugawana/keycloak-scim2-storage/commit/bcc0701752ef8057ce144d2266df507a16903536

This seems to work as I get log from later in the job execution:
![image](https://user-images.githubusercontent.com/77098658/154452823-520c5952-9de4-4485-ab36-2d678376eac2.png)

I'm a little astonished, is it correct? This doesn't fell right. Is it related to the old version I'm using?
I have little experience with Keycloak database model.

**Comment by suvera** [comment]
@sl-benoitoyez  I think **name** seems good fit.  But need to test with other versions too.

**Comment by sl-benoitoyez** [comment]
Okay, I'm opening a draft with the change for now. I'll see to test it in a more recent version ASAP.

**Comment by sl-benoitoyez** [comment]
I have tested this change in a Keycloak version 16.
Fixed in my PR, closing.
